test/structure/codeclimate-yml.test.js
test/structure/editorconfig.test.js
test/structure/ignore.test.js
test/structure/jsdoc-config.test.js
test/structure/packageJson.test.js

* Reduced duplication
* Cleaner assertions

Improved test assertion style

---

app.js
package.json

This pull request adds suitable configuration for CORS. 
* #153

Resolves #153

---

.gitignore
bin/www
package.json
scripts/app/restart.js
scripts/app/start.js
scripts/app/stop.js
scripts/test/index.js
scripts/test/security.js
test/structure/ignore.test.js
test/structure/packageJson.test.js
test/unit/utils/misc.test.js
utils/misc/index.js
utils/test/index.js

Most CLI style scripts in package.json have been replaced by their scripted equivalents. This would also make it easier to write route tests. Excessive fat has been trimmed where applicable, and issues with documentation have been fixed.
* #169

Resolves #169

---

app.js
bin/www
database/users.js
routes/api.js
routes/index.js
routes/users.js
scripts/app/restart.js
scripts/app/start.js
scripts/app/stop.js
scripts/database/purge.js
scripts/misc/pack.js
scripts/misc/postInstall.js
scripts/misc/test.js
scripts/test/e2e.js
scripts/test/esLint.js
scripts/test/index.js
scripts/test/security.js
scripts/test/structure.js
scripts/test/unit.js
utils/email/index.js
utils/misc/index.js
utils/passport.js
utils/test/index.js

Exhaustive documentation has been added for all applicable methods and files in the project.

Fixes #125

---

.eslintrc
app.js
bin/www.js
database/users.js
package.json
scripts/app/restart.js
scripts/app/start.js
scripts/app/stop.js
scripts/database/purge.js
scripts/misc/pack.js
scripts/misc/test.js
scripts/test/e2e.js
scripts/test/esLint.js
scripts/test/index.js
scripts/test/security.js
scripts/test/structure.js
scripts/test/unit.js
utils/passport.js
utils/test/index.js

* Updated JSDoc comments
* Updated ESLint configuration

Code style improvements

---

CHANGELOG.md

Added CHANGELOG.md (resolves #174)

---

package.json

fix(package): update uglify-js to version 2.8.7

---

package.json

Closes #252
https://greenkeeper.io/

fix(package): update raven to version 1.2.0

---

.eslintrc
test/unit/database/User.test.js

Adds tests for various cases under promise and callback style usage, with and without valid data of `User.find`:
* Find operations without query objects or literals.
* Find operations with query literals.
* Find operations with query objects.

User.find tests

---

test/unit/database/User.test.js

Added User.findOne unit tests

---

database/User.js
test/unit/database/User.test.js

Related to #63.
This pull request also fixes a bug resulting from incorrect Node MongoDB driver remove API usage.

User.deleteOne, User.delete unit tests

---

.eslintrc
database/User.js
test/unit/database/User.test.js

User.update* improvements + unit tests

---

.travis.yml
test/structure/travis-yml.test.js

Enabled travis osx builds

---

package.json
scripts/docs/make-wiki.js
test/structure/packageJson.test.js

Added script to generate wiki markdown

---

test/unit/database/User.test.js

Duplicate checks in `User` unit tests have been extracted into reusable helpers.

Trimmed User unit tests

---

package.json
scripts/app/start.js
scripts/misc/prestart.js
test/unit/scripts/prestart.test.js
test/unit/scripts/wiki.test.js

* Wiki generation
* Prestart script

Script unit tests

---

.eslintrc
package.json
scripts/package/archive.js
test/unit/scripts/package.test.js
test/unit/scripts/prestart.test.js
test/unit/scripts/wiki.test.js
utils/test/index.js

Adds a script to archive the contents of the current project state into a zipped archive based on the current branch name and the HEAD hash.

Added archive script

---

package.json

fix(package): update raven to version 1.2.1

---

.travis.yml
appveyor.yml
test/structure/appveyor-yml.test.js
test/structure/travis-yml.test.js

Even node builds

---

.eslintrc
app.js
bin/www.js
test/.eslintrc
utils/misc/index.js
utils/test/index.js

* Lodash and path are now globals within the code space.
* Application bootstrappers have been trimmed to a minimum.

Global scope cleanup

---

.eslintrc
database/User.js
utils/auth/passport.js
utils/misc/index.js

* `User` is now an accepted global.
* This pull request turns the passport utility into a require-able helper.
* New User code is now used within the passport util.

Passport utility update

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

This pull request addresses a bulk of the markdown linter warnings [here](https://codeclimate.com/github/kunagpal/express-boilerplate/code?q=.md)

Markdown beautification

---

.eslintrc
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
CHANGELOG.md
app.js
bin/www.js
routes/api.js
routes/home.js
routes/index.js
scripts/misc/postInstall.js
scripts/package/archive.js
test/structure/bower.test.js
test/unit/bootstrap.test.js
test/unit/utils/misc.test.js
utils/auth/passport.js
utils/misc/index.js
utils/test/index.js

This pull request aims to resolve a bunch of outstanding CodeClimate analysis issues.

Code compaction

---

package.json

Closes #317
https://greenkeeper.io/
* Description

chore(package): update eslint-plugin-jsdoc to version 3.0.2

---

scripts/test/index.js

Project tests now run without duplication.

Deduplicated project test suite (fixes #325)

---

README.md

Added doc quality badge

---

.github/ISSUE_TEMPLATE.md
CHANGELOG.md
scripts/database/purge.js
scripts/test/run.js
test/unit/bootstrap.test.js
test/unit/scripts/docs.test.js
utils/auth/passport.js

* Returns are more consistent within functions
* Markdown styling has been improved.

Linting improvements

---

scripts/misc/test.js
test/unit/scripts/app.test.js

* App start and stop scripts `npm start`, `npm stop` are now covered by unit tests.

Added app start, stop unit tests

---

inch.json
test/structure/inch.test.js
test/structure/singleton.test.js

* This pull request adds the configuration for Inch CI so that actual documentation quality metrics can be observed.

Inch CI config

---

app.js
scripts/docs/make-docs.js
scripts/docs/make-wiki.js
utils/test/index.js

As per https://inch-ci.org/github/kunagpal/express-boilerplate

Added missing JSDoc comments to methods

---

.travis.yml
test/structure/travis-yml.test.js

An attempt to fix the stalled Travis builds on Linux.

Disabled Linux builds

---

package.json

chore(package): update recursive-readdir to version 2.2.1

---

package.json

fix(package): update clean-css to version 4.1.3

---

package.json

fix(package): update uglify-js to version 3.0.10

---

bin/www.js
test/unit/bootstrap.test.js
utils/misc/index.js

* This allows a consistent cleanup mechanism across test and other envronments.

Added generic handler for SIGINT and error events

---

.gitignore
.travis.yml
appveyor.yml
test/structure/appveyor-yml.test.js
test/structure/travis-yml.test.js

Adds support for Node v8.x, fixes #285 
Blocked on https://github.com/appveyor/ci/issues/1581

Node v8.0.0 in CI

---

package.json

fix(package): update uglify-js to version 3.0.17

---

app.js
scripts/test/index.js
scripts/test/run.js
scripts/test/unit.js
test/unit/app/api/user.test.js

Injected models are now immutable and non-configurable.

Better models

---

routes/api.js
scripts/test/run.js
test/unit/app/api/user.test.js
utils/misc/index.js
utils/test/database.js

* Improved GET API tests for field projection logic.
* The test runner now respects the exit code for non-unit tests.
* Fixed field limiting logic in model maker.
* Improved username - email coherence in test user creation.

Better API tests

---

app.js
routes/api.js
scripts/test/run.js
test/unit/app/api/user.test.js
test/unit/bootstrap.test.js

* `app.js` now exposes test database `close` and `purge` helpers under the `test` environment
* The update RESTful route is now `PATCH` instead of `PUT`
* User REST API branch coverage has been improved slightly.
* The bootstrapper for the unit test application cleans up after itself a little better than before.
* Unit test code coverge is generated even if test errors occur.

Improved test flows

---

app.js
database/User.js
routes/api.js
scripts/test/run.js
test/unit/app/api/user.test.js
test/unit/bootstrap.test.js
test/unit/scripts/docs.test.js
utils/misc/index.js

Restful route improvements

---

.codeclimate.yml
package.json
test/structure/codeclimate-yml.test.js
test/structure/packageJson.test.js
utils/test/index.js

This pull request removes redundant code and alters the CodeClimate config to ignore the test suite for duplication checks.

CodeClimate config tweaks

---

app.js
routes/api.js
routes/home.js
scripts/test/run.js
test/unit/app/api/user.test.js
test/unit/app/index.test.js
utils/misc/index.js

* This pull request routes all the error handling for APIs through the application error handler.
* Some tests around this flow have also been added.
* Test coverage thresholds have been bumped up.
* Other redundancies have been removed.

Added suport for content-type negotiation to error responses

---

routes/api.js
utils/misc/index.js

Addresses existing CodeClimate issues.

Deduplicated code

---

README.md
package.json
scripts/misc/console.js
test/structure/packageJson.test.js

* With the pull request, `npm run console` will start a development console with the app and it's globals pre-loaded.

Resolved #433

---

routes/api.js
test/unit/utils/misc.test.js
utils/misc/index.js

Fixes all pending CodeClimate issues.

More deduplication
